use axum::Error;

#[tokio::main]
async fn main() -> Result<(), Error> {
  Ok(())
}